import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const notoSansKor = Noto_Sans_KR({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '@nkakmk',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/icon?<generated>',
      },
    ],
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <body className={notoSansKor.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
